### ISSUE TITLE
Add Nodes

### ISSUE THREAD

**Issue by DragonFlees** [Scribbles-MCAMK/Zelcash-Wallet#1]
New to this and not sure where to add the node commands you listed.  please help

**Comment by extrazeldev** [comment]
Nodes can be added in your zelcash.conf file

[WINDOWS]
Navigate to %APPDATA%\Zelcash 
Open the zelcash.conf file and append this to the bottom

addnode=node.zel.cash
addnode=45.63.86.148
addnode=199.247.8.181
addnode=45.76.128.62
addnode=45.76.186.252

**Comment by DragonFlees** [comment]
Thank you
