### ISSUE TITLE
Unable to sync, remains at 98.63% with 5 Connections.

### ISSUE THREAD

**Issue by ddelapaz** [Scribbles-MCAMK/Zelcash-Wallet#4]
I made sure firewall is not blocking, attempted to hotspot from my phone and it just stays at 98.63%. I added the extra nodes and nothing. Also tried the latest version 0.0.2 and no luck.

I sometimes get 5 connections on the bottom right corner of the wallet, the 2 arrows go gray/black from their red color,  but still, the percent remains at 98.63%.

I deleted all files but `wallet.dat` and `zelcash.config` from the `AppData` directory as recommended by someone in https://bitcointalk.org/index.php?topic=2853688.0 but that made no difference. I even deleted the `zelcash.config` to allow the app to recreate it. No difference.

Any idea what may be happening? 
![screen shot 2018-02-01 at 2 49 44 pm](https://user-images.githubusercontent.com/10531886/35704157-8f67d422-076c-11e8-9e74-3de199363713.png)

**Comment by extrazeldev** [comment]
Since you follow the directions I assume you added these nodes but I have to ask just to be safe.

addnode=node.zel.cash
addnode=45.63.86.148
addnode=199.247.8.181
addnode=45.76.128.62
addnode=45.76.186.252

**Comment by ddelapaz** [comment]
We can close this thread, yeah I added the nodes. It works as intended on my home network. I was at work and I guess using my cell carrier's LTE network also didn't work. Once I got home I sync just fine and my coins showed up. Thanks

**Comment by extrazeldev** [comment]
Happy to hear it. Thank you for the update.
