### ISSUE TITLE
error: couldn't connect to server: EOF reached (code 1) on wallet start. 

### ISSUE THREAD

**Issue by siliconunit** [Scribbles-MCAMK/Zelcash-Wallet#6]
error: couldn't connect to server: EOF reached (code 1) on wallet start. 
I get this when running the wallet jar file ( or any file) wallet worked properly the first time it started , but after a clean reboot of machine I get this.

**Comment by deonisij2018** [comment]
same problem for me!

**Comment by siliconunit** [comment]
running zelcashd -reindex worked

**Comment by extrazeldev** [comment]
Self-solutions are the best. I apologize for the delay in my response.
